/**************************************************************************
-- -Generated by xSQL SDK for Schema Comparison and Synchronization
-- -Date/Time: September 11, 2013 10:45:52

-- -Summary:
    Contains the T-SQL script that makes the database 
    sttitestsql01.avhost.ld.netFORUMSTTITEST the same as the database sttitestsql01.avhost.ld.netForumSTTIDev

-- -Action:
    Execute this script on sttitestsql01.avhost.ld.netFORUMSTTITEST

-- -SQL Server version: 10.50.4000
**************************************************************************/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[client_stti_email_blueprint] (
	[i13_key] [dbo].[av_key] ROWGUIDCOL NOT NULL,
	[i13_add_user] [dbo].[av_user] NOT NULL,
	[i13_add_date] [dbo].[av_date] NOT NULL,
	[i13_change_user] [dbo].[av_user] NULL,
	[i13_change_date] [dbo].[av_date] NULL,
	[i13_delete_flag] [dbo].[av_delete_flag] NOT NULL,
	[i13_entity_key] [dbo].[av_key] NULL,
	[i13_bh_template_id] [int] NULL,
	[i13_code] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[i13_description] [nvarchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[i13_send_logic] [nvarchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[i13_customization] [dbo].[av_flag] NOT NULL,
	[i13_recipient_query] [nvarchar](300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[i13_i12_key] [dbo].[av_key] NULL,
	[i13_recipient_type] [nvarchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[i13_amsconnect_object_type] [nvarchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[client_stti_email_blueprint] ADD 
	CONSTRAINT [DF_client_stti_email_blueprint_i13_add_date] DEFAULT (getdate()) FOR [i13_add_date]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[client_stti_email_blueprint] ADD 
	CONSTRAINT [DF_client_stti_email_blueprint_i13_add_user] DEFAULT (suser_sname()) FOR [i13_add_user]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[client_stti_email_blueprint] ADD 
	CONSTRAINT [DF_client_stti_email_blueprint_i13_chapter_customization] DEFAULT ((0)) FOR [i13_customization]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[client_stti_email_blueprint] ADD 
	CONSTRAINT [DF_client_stti_email_blueprint_i13_delete_flag] DEFAULT ((0)) FOR [i13_delete_flag]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[client_stti_email_blueprint] ADD 
	CONSTRAINT [DF_client_stti_email_blueprint_i13_key] DEFAULT (newid()) FOR [i13_key]
GO

SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [HRS].vw_client_stti_EmailBlueprint
AS

	SELECT
		i13_key AS BlueprintId,
		i13_code AS Code,
		i13_description AS Description,
		i13_bh_template_id AS BHTemplateId,
		i13_send_logic AS SendLogic,
		i13_recipient_type AS RecipientType,
		i13_recipient_query AS RecipientQuery,
		i13_i12_key AS TriggerTypeKey,
		i13_customization AS CustomizationAllowed,
		i13_amsconnect_object_type AS AMSConnectObjectType,
		i13_delete_flag AS IsDeleted
	FROM
		client_stti_email_blueprint (NOLOCK)
GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [HRS].client_stti_Blueprint_GetAllRecords
AS

	SELECT
		*
	FROM
		[HRS].vw_client_stti_EmailBlueprint (NOLOCK)

GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [HRS].client_stti_Blueprint_GetRecordById
	@BlueprintId UNIQUEIDENTIFIER
AS

	SELECT
		*
	FROM
		[HRS].vw_client_stti_EmailBlueprint (NOLOCK)
	WHERE
		IsDeleted = 0
		AND BlueprintId = @BlueprintId
GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
if not exists (select * from sys.objects where [name] = N'PK_client_stti_email_blueprint' and [type] = 'PK')
ALTER TABLE [dbo].[client_stti_email_blueprint] ADD 
	CONSTRAINT [PK_client_stti_email_blueprint] PRIMARY KEY CLUSTERED 
	(
		[i13_key]
	) ON [PRIMARY];
GO

