/**************************************************************************
-- -Generated by xSQL SDK for Schema Comparison and Synchronization
-- -Date/Time: September 11, 2013 10:53:53

-- -Summary:
    Contains the T-SQL script that makes the database 
    sttitestsql01.avhost.ld.netFORUMSTTITEST the same as the database sttitestsql01.avhost.ld.netForumSTTIDev

-- -Action:
    Execute this script on sttitestsql01.avhost.ld.netFORUMSTTITEST

-- -SQL Server version: 10.50.4000
**************************************************************************/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[client_stti_email_trigger_type] (
	[i12_key] [dbo].[av_key] ROWGUIDCOL NOT NULL,
	[i12_add_user] [dbo].[av_user] NOT NULL,
	[i12_add_date] [dbo].[av_date] NOT NULL,
	[i12_change_user] [dbo].[av_user] NULL,
	[i12_change_date] [dbo].[av_date] NULL,
	[i12_delete_flag] [dbo].[av_delete_flag] NOT NULL,
	[i12_entity_key] [dbo].[av_key] NULL,
	[i12_code] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[i12_description] [nvarchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[client_stti_email_trigger_type] ADD 
	CONSTRAINT [DF_client_stti_email_trigger_type_i12_add_date] DEFAULT (getdate()) FOR [i12_add_date]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[client_stti_email_trigger_type] ADD 
	CONSTRAINT [DF_client_stti_email_trigger_type_i12_add_user] DEFAULT (suser_sname()) FOR [i12_add_user]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[client_stti_email_trigger_type] ADD 
	CONSTRAINT [DF_client_stti_email_trigger_type_i12_delete_flag] DEFAULT ((0)) FOR [i12_delete_flag]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[client_stti_email_trigger_type] ADD 
	CONSTRAINT [DF_client_stti_email_trigger_type_i12_key] DEFAULT (newid()) FOR [i12_key]
GO

SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [HRS].vw_client_stti_EmailTriggerType
AS

	SELECT
		i12_key AS TriggerTypeId,
		i12_code AS Code,
		i12_description AS Description,
		i12_delete_flag AS IsDeleted
	FROM
		client_stti_email_trigger_type (NOLOCK)

GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [HRS].client_stti_TriggerType_GetAllRecords
AS

	SELECT
		*
	FROM
		[HRS].vw_client_stti_EmailTriggerType (NOLOCK)
GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
if not exists (select * from sys.objects where [name] = N'PK_client_stti_email_trigger_type' and [type] = 'PK')
ALTER TABLE [dbo].[client_stti_email_trigger_type] ADD 
	CONSTRAINT [PK_client_stti_email_trigger_type] PRIMARY KEY CLUSTERED 
	(
		[i12_key]
	) ON [PRIMARY];
GO

