/**************************************************************************
-- -Generated by xSQL SDK for Schema Comparison and Synchronization
-- -Date/Time: September 11, 2013 10:50:35

-- -Summary:
    Contains the T-SQL script that makes the database 
    sttitestsql01.avhost.ld.netFORUMSTTITEST the same as the database sttitestsql01.avhost.ld.netForumSTTIDev

-- -Action:
    Execute this script on sttitestsql01.avhost.ld.netFORUMSTTITEST

-- -SQL Server version: 10.50.4000
**************************************************************************/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[client_stti_email_calendar] (
	[i14_key] [dbo].[av_key] ROWGUIDCOL NOT NULL,
	[i14_add_user] [dbo].[av_user] NOT NULL,
	[i14_add_date] [dbo].[av_date] NOT NULL,
	[i14_change_user] [dbo].[av_user] NULL,
	[i14_change_date] [dbo].[av_date] NULL,
	[i14_delete_flag] [dbo].[av_delete_flag] NOT NULL,
	[i14_entity_key] [dbo].[av_key] NULL,
	[i14_i13_key] [dbo].[av_key] NULL,
	[i14_instance_key] [dbo].[av_key] NULL,
	[i14_send_date] [dbo].[av_date] NULL,
	[i14_status] [dbo].[av_integer] NULL,
	[i14_custom_text] nvarchar(max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[i14_start_date] [dbo].[av_date] NULL,
	[i14_completion_date] [dbo].[av_date] NULL,
	[i14_custom_subject] nvarchar(max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[client_stti_email_calendar] ADD 
	CONSTRAINT [DF_client_stti_email_calendar_i14_add_date] DEFAULT (getdate()) FOR [i14_add_date]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[client_stti_email_calendar] ADD 
	CONSTRAINT [DF_client_stti_email_calendar_i14_add_user] DEFAULT (suser_sname()) FOR [i14_add_user]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[client_stti_email_calendar] ADD 
	CONSTRAINT [DF_client_stti_email_calendar_i14_delete_flag] DEFAULT ((0)) FOR [i14_delete_flag]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[client_stti_email_calendar] ADD 
	CONSTRAINT [DF_client_stti_email_calendar_i14_key] DEFAULT (newid()) FOR [i14_key]
GO

SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [HRS].vw_client_stti_EmailCalendar
AS

	SELECT
		i14_key AS CalendarId,
		i14_i13_key AS BlueprintKey,
		i14_instance_key AS ObjectInstanceKey,
		i14_send_date AS SendDate,
		i14_status AS SendStatus,
		i14_custom_text AS CustomText,
		i14_custom_subject AS CustomSubjectLine,
		i14_start_date AS SendStartDate,
		i14_completion_date AS SendCompletionDate,
		i14_delete_flag AS IsDeleted
	FROM
		client_stti_email_calendar (NOLOCK)

GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [HRS].client_stti_Calendar_GetAllRecords
AS
	
	SELECT
		*
	FROM
		[HRS].vw_client_stti_EmailCalendar (NOLOCK)

GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [HRS].client_stti_Calendar_GetRecordById
	@CalendarId	UNIQUEIDENTIFIER
AS

	
	SELECT
		*
	FROM
		[HRS].vw_client_stti_EmailCalendar (NOLOCK)
	WHERE
		IsDeleted = 0
		AND CalendarId = @CalendarId
GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
if not exists (select * from sys.objects where [name] = N'PK_client_stti_email_calendar' and [type] = 'PK')
ALTER TABLE [dbo].[client_stti_email_calendar] ADD 
	CONSTRAINT [PK_client_stti_email_calendar] PRIMARY KEY CLUSTERED 
	(
		[i14_key]
	) ON [PRIMARY];
GO

